research_task:
  description: >
    Search for CURRENT AI/ML, Data Engineering, and Data Science job opportunities in Turkey (prioritize) and remote positions that match Özgür's profile:
    
    Target Skills to Match:
    - Programming: Python, JavaScript, Go, SQL
    - AI/ML: OpenAI API, LangChain, spaCy, scikit-learn, TensorFlow, RAG systems
    - Data: ETL processes, BigQuery, PostgreSQL, MongoDB
    - Backend: FastAPI, microservices, gRPC
    
    Search Criteria:
    - Job platforms: LinkedIn, Kariyer.net, Glassdoor, Indeed Turkey
    - Location: Turkey (especially Istanbul) + Remote globally  
    - Company size: 11+ employees
    - Job posting age: Posted today Last 24 hours only 
    - Job types: Remote, Hybrid, On-site

    IMPORTANT: Use these specific search queries in order:
    1. "AI machine learning jobs Istanbul "
    2. "Veri mühendisi işleri Istanbul "  
    3. "Data scientist Turkey "
    4. "Remote AI developer jobs "
    
    For each job found, extract:
    - Job title and company name
    - Location and work type (remote/hybrid/onsite)
    - Salary information (if available)
    - Job description summary
    - Key requirements and technologies mentioned
    - Experience level required
    - Direct URL to job posting
    - Date when job was posted

    REJECT any job posting from 2023 or earlier years.
    Focus on quality over quantity - return only jobs that are genuinely relevant
    to Özgür's AI/ML and data engineering background.

    FINAL STEP: After collecting all job data, use the job_database_saver tool to save 
    all found jobs to the database. Format the jobs as a JSON array and pass it to the tool.

  expected_output: >
    A structured JSON report containing:
    - Search metadata (keyword used, total jobs found, search date)
    - List of relevant job opportunities with complete details:
      * title, company, location, salary
      * description summary and key requirements  
      * technologies and tools mentioned
      * experience level and work type
      * job posting URL and date found
    
    Minimum 5 jobs, maximum 15 high-quality matches.
    Each job entry must include all required fields.

  agent: researcher
