research_task:
  description: >
    STEP 1 - ANALYZE CV FIRST:
    Use the PDFSearchTool to analyze Özgür's CV and extract key information before starting job search.
    
    Extract the following information from the CV:
    - Current technical skills and programming languages 
    - Recent work experience and technologies used
    - AI/ML expertise and tools (OpenAI, LangChain, etc.)
    - Data engineering technologies (PostgreSQL, MongoDB, etc.)
    - Location preferences and experience level
    
    Use queries like:
    - "technical skills programming languages Python JavaScript"
    - "AI machine learning OpenAI LangChain experience"
    - "data engineering PostgreSQL MongoDB BigQuery"
    - "recent work experience technologies projects"
    
    STEP 2 - CREATE PERSONALIZED SEARCH QUERIES:
    Based on the CV analysis, create 3-4 targeted job search queries that match 
    Özgür's actual skills and experience. Focus on the most relevant technologies found in the CV.
    
    STEP 3 - SEARCH FOR JOBS:
    Use your personalized queries to search for AI/ML, Data Engineering, and Data Science 
    job opportunities in Turkey and remote positions.
    
    Search Criteria:
    - Job platforms: LinkedIn, Kariyer.net, Glassdoor, Indeed Turkey
    - Location: Turkey (especially Istanbul) + Remote globally  
    - Company size: 11+ employees
    - Job posting age: Last 24 hours only 
    - Job types: Remote, Hybrid, On-site
    
    For each job found, extract:
    - Job title and company name
    - Location and work type (remote/hybrid/onsite)
    - Salary information (if available)
    - Job description summary
    - Key requirements and technologies mentioned
    - Experience level required
    - Direct URL to job posting
    - Date when job was found

    REJECT any job posting from 2023 or earlier years.
    Focus on quality over quantity - return only jobs that genuinely match 
    the skills extracted from Özgür's CV.

    STEP 4 - SAVE TO DATABASE:
    After collecting all job data, use the job_database_saver tool to save 
    all found jobs to the database. Format the jobs as a JSON array.

  expected_output: >
    A structured JSON report containing:
    - Search metadata (keyword used, total jobs found, search date)
    - List of relevant job opportunities with complete details:
      * title, company, location, salary
      * description summary and key requirements  
      * technologies and tools mentioned
      * experience level and work type
      * job posting URL and date found
    
    Minimum 5 jobs, maximum 15 high-quality matches.
    Each job entry must include all required fields.

  agent: researcher
